name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16   # ← Cambiado de node:16-alpine a node:16

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Prepare Lunr UI
        run: |
          mkdir -p supplemental-ui
          cp -R node_modules/@antora/lunr-extension/supplemental_ui/* supplemental-ui/

      - name: Create images folder
        run: mkdir -p docs/despliegue-continuo/0.22.2/_images

      - name: Fix permissions
        run: chmod -R 777 docs/despliegue-continuo/0.22.2/_images

      - name: Build Antora project
        run: npx antora local-antora-playbook.yml --fetch